### ISSUE TITLE
Settings Page Form Validation

### ISSUE THREAD

**Issue by mmikhan** [vardump/optimus#16]
All of the forms the are available on the [settings page](https://github.com/vardump/optimus/blob/master/resources/views/settings.blade.php) needs to be added the `required` validation. Without the `required` attribute, when the form is blank and you hit the `Save` or `Sync now` button, the Success modal still shows, which should never.

**Comment by prappo** [comment]
fixed @ https://github.com/vardump/optimus/commit/7340deea71da513efa045761d3fd747602823222
