### ISSUE TITLE
Fix the Register Page View

### ISSUE THREAD

**Issue by mmikhan** [vardump/optimus#4]
Register page is still showing the Laravel default view. Add the AdminLTE register page view.

**Comment by prappo** [comment]
what about register button . would it be along side login button on login page ?

**Comment by mmikhan** [comment]
Register button would be only on the Login page. However, we can place a Login button on the Register page, too.

**Comment by prappo** [comment]
solved commit https://github.com/vardump/optimus/commit/2ad7a7e3bb9a0e9bbfa2058be4f947d51058994b
