### ISSUE TITLE
img directory

### ISSUE THREAD

**Issue by mmikhan** [vardump/optimus#7]
Not sure whether the `public/img` directory is still needed.

**Comment by prappo** [comment]
yes , all because all basic image contain this folder like facebook , twitter etc and especially for optimus's logo

**Comment by mmikhan** [comment]
All the images should be under the `images` folder, not the `img` one

**Comment by prappo** [comment]
`images` folder create by gulp  so it would overwrite with default `images` folder and main image contents will be lost and this is why i named it `img`

**Comment by mmikhan** [comment]
Gulp doesn't override anything. We can still make it work. Just give me your confirmation about the images that is located in the `img` directory. Do we still need it as you have used a new Emoji library?
