### ISSUE TITLE
skypephp_cache directory

### ISSUE THREAD

**Issue by mmikhan** [vardump/optimus#8]
Not sure what do we do with the `public/skypephp_cache` directory.

**Comment by prappo** [comment]
skypephp_cache dir create when skype method fire . it help for less api call

**Comment by mmikhan** [comment]
Sounds good. So, we need to add that directory to the `.gitignore` file as we don't want to include it on the repository.

**Comment by mmikhan** [comment]
resolved https://github.com/vardump/optimus/commit/160bb9f26effa910c43e1e51fbd685cb52d61e02
